import type { Metadata } from "next";
import Appbar from "@/components/Appbar";
import { Providers } from "@/components/Providers";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={"ds"}>
        <Providers>
          <main className="w-9/12 mx-auto">
            <Appbar />
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
